[package]
name = "spl-pod"
version = "0.4.0"
description = "Solana Program Library Plain Old Data"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.18.0", features = ["derive", "min_const_generics"] }
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", rev = "5208a7870826307290c30b7d80768f40267433a1" }
thiserror = "1.0.63"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.2"

[lib]
crate-type = ["cdylib", "lib"]
